export const initialMockData = {
  full_name: '',
  profession: '',
  company: '',
  location: '',
  bio: '',
  avatar_url: '',
  theme_color: '#10B981',
  is_dark_mode: false,
  slug: '',
  vcard_enabled: true,
  whatsapp: '',
  contact_phone: '',
  contact_email: '',
  website_url: '',
  website: '',
  linkedin: '',
  instagram: '',
  facebook: '',
  bank_enabled: false,
  bank_name: '',
  bank_type: '',
  bank_number: '',
  bank_rut: '',
  bank_email: '',
  calendar_url: '',
  portfolio_url: '',
};

export const defaultLandingContent = {
  heroTitle: 'Conecta Mejor',
  heroAccent: 'Hoy',
  heroBadge: 'NexCard MVP',
  heroDescription: 'La tarjeta de presentación inteligente que evoluciona con tu negocio.',
  primaryCta: 'Comenzar',
  socialProof: '100+ Profesionales',
  finalCtaTitle: '¿Listo para el siguiente nivel?',
  finalCtaButton: 'Crear mi Tarjeta'
};
